disabled_rules: # rule identifiers to exclude from running
  - line_length # no limit on length of line
  - trailing_whitespace # be able to one empty line
  - large_tuple # tuple can hold values more than three
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - libpd-Swift-sample
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
#   line_length: 256
# they can set both implicitly with an array
type_body_length:
  - 1500 # warning
  - 3000 # error
function_body_length:
  - 500 # warning
  - 1000 # error
# or they can set both explicitly
file_length:
  warning: 1500
  error: 3000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  min_length: 1 # single letter name is fine
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
